### ISSUE TITLE
Segfault when running test_simple

### ISSUE THREAD

**Issue by lantiga** [ezyang/pytorch-unattached#32]
Hi @ezyang, I'd like to get my hands dirty with the IR code (great stuff BTW). I just built the `jit` branch and ran `test_simple`

```
x = Variable(torch.Tensor([0.4]), requires_grad=True)
y = Variable(torch.Tensor([0.7]), requires_grad=True)

torch._C._tracer_enter((x, y))
z = torch.sigmoid(torch.tanh(x * (x + y)))
trace = torch._C._tracer_exit((z,))
```

I get a segfault right at the last line. The segfault is due to `THPGraphClass` being `nullptr` in `THPGraph_Wrap` (in `torch/csrc/jit/python_ir.cpp`), in turn called at line 64 in `torch/csrc/jit/python_tracer.cpp`.

Apparently `THPJIT_initExtension` (in `torch/csrc/jit/init.cpp`) is never executed for me, so `THPGraphClass` is not initialized. Is there anything I'm missing on my end?

Thanks!

**Comment by ezyang** [comment]
Oh! This is a bit awful, but as of  038348d   you need to import `torch.jit`, since that is what actually does initialization (even though you can call the _tracer_enter/_tracer_exit functions without having touched the initialization path.) We should fix this.

Also, credit where credit is due: the JIT is a joint effort between me, @zdevito and @apaszke, and at this point, most of the code was not written by me ;)

**Comment by apaszke** [comment]
#34 fixes that

**Comment by apaszke** [comment]
But in general it's reasonable to require people to import `torch.jit` before they use these functions. They normally should never be used directly

**Comment by lantiga** [comment]
Thank you @ezyang and @apaszke !
