### ISSUE TITLE
Lifetime for Type objects associated with nodes makes me nervous

### ISSUE THREAD

**Issue by ezyang** [ezyang/pytorch-unattached#52]
In particular, we have a public `setType()` function which has the effect of invalidating any `Type*` pointers returned from `type()`. This feels error-prone.

**Comment by apaszke** [comment]
We should just depend on unique_ptrs to manage their lifetime

**Comment by zdevito** [comment]
Reposting from review: In the long term, I think we should copy LLVM and make types immutable, sharing them across all values of that type so that type equality is (&t1 == &t2). We can refcount them since they won't have cycles. It will make most passes that are just preserving the type information easier to manage since we won't have to clutter them with type copies. I've done this before even with size/stride information as part of the type -- there are not that many unique combinations in a network.

**Comment by zdevito** [comment]
#58 makes types shared pointers to immutable objects, shared among multiple nodes, potentially. This is one step towards type equality being pointer equality that solves the invalidation problems.

**Comment by ezyang** [comment]
Now that we used shared pointers the immediate problem is gone.
