### ISSUE TITLE
Helper function for jitting functions

### ISSUE THREAD

**Issue by ezyang** [ezyang/pytorch-unattached#55]
We have a helper that works for models, but nothing for plain old functions.

**Comment by zdevito** [comment]
I think we probably need to refactor the current interface because we need to handle a number of different cases of objects and actions:

Objects we work on:
1. (low-level) 0-arg function, with explicit list of input variables
2. a full model, assuming forward()'s variables + .parameters() as input variables
3. a function that takes arguments. we add an additional keyword argument model_parameters to the wrapped function.

Actions we do:
1. run the object once and return the trace as an object for export
2. wrap the object so that after the first time, execution goes through the trace, possibly timing the result
3. wrap the object, verifying at every iteration that we get the same result from the trace as from the original, possibly timing
4. wrap the object, but don't do any tracing, just do timing (useful for timing fusedLSTM, which we can't trace)


I think we can make this simple by turning objects (2) and (3) into object (1), and then factoring the common functions out of actions 1--4.
I'm going to try to get this in tomorrow so that we can present a more consistent interface to users.

**Comment by zdevito** [comment]
#60
